## Amazon Customer Reviews Analysis

In [1]:
import pandas as pd
import os

In [2]:
import os

os.listdir("../data")

['amazon_reviews_us_Video_Games_v1_00.tsv',
 'amazon_reviews_us_Mobile_Electronics_v1_00.tsv',
 'amazon_reviews_us_Electronics_v1_00.tsv']

In [3]:
import os
os.getcwd()

'/home/seval/Amazon-Customer-Reviews/notebooks'

In [4]:
import pandas as pd

file_path = "../data/amazon_reviews_us_Video_Games_v1_00.tsv"

df = pd.read_csv(
    file_path,
    sep="\t",
    nrows=5,
    engine="python"
)

df.head()

,marketplace,customer_id,review_id,product_id,product_parent,product_title,product_category,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_date
0,US,12039526,RTIS3L2M1F5SM,B001CXYMFS,737716809,Thrustmaster T-Flight Hotas X Flight Stick,Video Games,5,0,0,N,Y,an amazing joystick. I especially love that yo...,"Used this for Elite Dangerous on my mac, an am...",2015-08-31
1,US,9636577,R1ZV7R40OLHKD,B00M920ND6,569686175,Tonsee 6 buttons Wireless Optical Silent Gamin...,Video Games,5,0,0,N,Y,Definitely a silent mouse... Not a single clic...,"Loved it, I didn't even realise it was a gami...",2015-08-31
2,US,2331478,R3BH071QLH8QMC,B0029CSOD2,98937668,Hidden Mysteries: Titanic Secrets of the Fatef...,Video Games,1,0,1,N,Y,One Star,poor quality work and not as it is advertised.,2015-08-31
3,US,52495923,R127K9NTSXA2YH,B00GOOSV98,23143350,GelTabz Performance Thumb Grips - PlayStation ...,Video Games,3,0,0,N,Y,"good, but could be bettee","nice, but tend to slip away from stick in inte...",2015-08-31
4,US,14533949,R32ZWUXDJPW27Q,B00Y074JOM,821342511,Zero Suit Samus amiibo - Japan Import (Super S...,Video Games,4,0,0,N,Y,Great but flawed.,"Great amiibo, great for collecting. Quality ma...",2015-08-31

In [5]:
import pandas as pd

use_cols = [
    "review_id",
    "product_title",
    "product_category",
    "star_rating",
    "review_headline",    
    "review_body",
    "verified_purchase"
]

In [6]:
chunks = pd.read_csv(
    "../data/amazon_reviews_us_Video_Games_v1_00.tsv",
    sep="\t",
    usecols=use_cols+ ["review_date"],
    chunksize=100_000
)

In [7]:
df_chunk = next(chunks)
df_chunk.head()

,review_id,product_title,product_category,star_rating,verified_purchase,review_headline,review_body,review_date
0,RTIS3L2M1F5SM,Thrustmaster T-Flight Hotas X Flight Stick,Video Games,5,Y,an amazing joystick. I especially love that yo...,"Used this for Elite Dangerous on my mac, an am...",2015-08-31
1,R1ZV7R40OLHKD,Tonsee 6 buttons Wireless Optical Silent Gamin...,Video Games,5,Y,Definitely a silent mouse... Not a single clic...,"Loved it, I didn't even realise it was a gami...",2015-08-31
2,R3BH071QLH8QMC,Hidden Mysteries: Titanic Secrets of the Fatef...,Video Games,1,Y,One Star,poor quality work and not as it is advertised.,2015-08-31
3,R127K9NTSXA2YH,GelTabz Performance Thumb Grips - PlayStation ...,Video Games,3,Y,"good, but could be bettee","nice, but tend to slip away from stick in inte...",2015-08-31
4,R32ZWUXDJPW27Q,Zero Suit Samus amiibo - Japan Import (Super S...,Video Games,4,Y,Great but flawed.,"Great amiibo, great for collecting. Quality ma...",2015-08-31

In [8]:
df_chunk["sentiment"] = df_chunk["star_rating"].apply(
    lambda x: "positive" if x >= 4 else "negative"
)

In [9]:
for chunk in chunks:
    chunk["sentiment"] = ...
    chunk.to_csv("processed.csv", mode="a", header=False)

In [10]:
for chunk in chunks:
    print(chunk["product_category"].value_counts())

In [11]:
files = [
    "../data/amazon_reviews_us_Video_Games_v1_00.tsv",
    "../data/amazon_reviews_us_Electronics_v1_00.tsv",
    "../data/amazon_reviews_us_Mobile_Electronics_v1_00.tsv"
]

In [12]:
import pandas as pd

df_list = []

for file in files:
    df = pd.read_csv(
        file,
        sep="\t",
        usecols=use_cols,
        encoding="utf-8",
        on_bad_lines="skip"
    )
    
    df_list.append(df)

final_df = pd.concat(df_list, ignore_index=True)

In [13]:
final_df = final_df[
    final_df["product_category"].isin([
        "Electronics",
        "Video Games",
        "Mobile_Electronics"
    ])
]

In [14]:
final_df["product_category"].value_counts()

product_category
Electronics           3091103
Video Games           1780280
Mobile_Electronics     104852
Name: count, dtype: int64

In [15]:
df_sample = final_df.sample(200000, random_state=42)

In [16]:
print(df_sample.shape)
df_sample.head()

(200000, 7)

,review_id,product_title,product_category,star_rating,verified_purchase,review_headline,review_body
3650245,R3SE4FJ5C1YK2Z,"XO Vision Mobile Headphones, Universal Wireles...",Electronics,5.0,Y,Love these,I bought these for a roadtrip for my daughter....
523642,R1YIS8SE2IPJP3,Uncharted 3: Drake'S Deception Game Of The Yea...,Video Games,4.0,N,First of all I absolutely love the Uncharted s...,First of all I absolutely love the Uncharted s...
3031670,R1QBCRRQ5FCPWX,August DTA230 Digital TV Antenna - Portable In...,Electronics,1.0,Y,Rabbit eras work better.,Does nothing. Rabbit eras work better.
3236760,R3JWWAJ05YJGLX,PCT 8 Port Bi-Directional Cable TV Splitter Si...,Electronics,4.0,Y,Works very well,I have two of these for my house. They work a...
4756741,R2P6O1AHTL5EXN,Koss KSC75 Portable Stereophone Headphones,Electronics,2.0,N,2 words: sound leakage,i didn't like them because of the sound leakag...

In [17]:
final_df["product_category"].value_counts()

product_category
Electronics           3091103
Video Games           1780280
Mobile_Electronics     104852
Name: count, dtype: int64

In [18]:
df_sample["product_category"].value_counts()

product_category
Electronics           124363
Video Games            71467
Mobile_Electronics      4170
Name: count, dtype: int64

(burada class imbalance nedeniyle ; class_weight = "balanced" kullanılmalı )

In [19]:
df_sample["product_category"].unique()

array(['Electronics', 'Video Games', 'Mobile_Electronics'], dtype=object)

In [20]:
df_sample["product_category"] = df_sample["product_category"].str.strip()

In [21]:
df_sample.head()

,review_id,product_title,product_category,star_rating,verified_purchase,review_headline,review_body
3650245,R3SE4FJ5C1YK2Z,"XO Vision Mobile Headphones, Universal Wireles...",Electronics,5.0,Y,Love these,I bought these for a roadtrip for my daughter....
523642,R1YIS8SE2IPJP3,Uncharted 3: Drake'S Deception Game Of The Yea...,Video Games,4.0,N,First of all I absolutely love the Uncharted s...,First of all I absolutely love the Uncharted s...
3031670,R1QBCRRQ5FCPWX,August DTA230 Digital TV Antenna - Portable In...,Electronics,1.0,Y,Rabbit eras work better.,Does nothing. Rabbit eras work better.
3236760,R3JWWAJ05YJGLX,PCT 8 Port Bi-Directional Cable TV Splitter Si...,Electronics,4.0,Y,Works very well,I have two of these for my house. They work a...
4756741,R2P6O1AHTL5EXN,Koss KSC75 Portable Stereophone Headphones,Electronics,2.0,N,2 words: sound leakage,i didn't like them because of the sound leakag...

In [22]:
df_sample.shape

(200000, 7)

In [23]:
df_sample.columns

Index(['review_id', 'product_title', 'product_category', 'star_rating',
       'verified_purchase', 'review_headline', 'review_body'],
      dtype='object')

In [24]:
df_sample.dtypes

review_id             object
product_title         object
product_category      object
star_rating          float64
verified_purchase     object
review_headline       object
review_body           object
dtype: object

In [25]:
df_sample.isna().sum().sort_values(ascending=False)

review_body          7
review_headline      2
review_id            0
product_title        0
product_category     0
star_rating          0
verified_purchase    0
dtype: int64

Metin içermeyen kullanıcı geri bildirimleri, doğal dil işleme modelleri tarafından analiz edilemeyeceği için sistem tarafından erken aşamada filtrelenmiştir.

In [26]:
df_sample = df_sample.dropna(subset=["review_body"])

In [27]:
df_sample["star_rating"].value_counts().sort_index()

star_rating
1.0     22846
2.0     11482
3.0     15980
4.0     35144
5.0    114541
Name: count, dtype: int64

In [28]:
df_sample.shape

(199993, 7)

In [29]:
df_sample["is_problem"] = (df_sample["star_rating"] <= 3).astype(int)

Kullanıcı değerlendirmelerinde 3 yıldız ve altı puanlar problemli geri bildirimler olarak etiketlenmiş, 4 ve 5 yıldızlı yorumlar problemsiz olarak kabul edilmiştir. Bu yaklaşım müşteri deneyimi literatürü ve pratik destek süreçleriyle uyumludur.

In [30]:
df_sample["is_problem"].value_counts(normalize=True)

is_problem
0    0.748451
1    0.251549
Name: proportion, dtype: float64

Etiketleme sonucunda verinin %25.1’i problemli, %74.9’u problemsiz geri bildirimlerden oluşmaktadır. Bu dağılım, müşteri geri bildirim sistemlerinde sıklıkla gözlemlenen gerçekçi bir dengesizlik yapısını yansıtmaktadır.

In [31]:
pd.crosstab(
    df_sample["product_category"],
    df_sample["is_problem"],
    normalize="index"
)

is_problem                 0         1
product_category
Electronics         0.749101  0.250899
Mobile_Electronics  0.668106  0.331894
Video Games         0.752008  0.247992

Kategori bazlı analiz sonucunda Mobile Electronics ürünlerinde problemli geri bildirim oranının %33 ile diğer kategorilere kıyasla belirgin şekilde daha yüksek olduğu gözlemlenmiştir. Bu durum, küçük ve taşınabilir elektronik ürünlerde kullanıcı beklentilerinin daha sık karşılanmamasıyla ilişkilendirilebilir.

In [32]:
df_sample["review_length"] = df_sample["review_body"].str.len()

In [33]:
df_sample["review_length"].describe()

count    199993.000000
mean        427.671999
std         799.828721
min           1.000000
25%         104.000000
50%         196.000000
75%         452.000000
max       29418.000000
Name: review_length, dtype: float64

Yorumların çoğu kısa ve orta uzunlukta. Ancak çok az sayıda aşırı uzun yorum ortalamayı yükseltiyor. Bu aşırı uzun yorumlar modelleme sırasında gürültü olarak değerlendirilebilir ve temizlenmelidir.

In [34]:
df_sample.nlargest(10, "review_length")[["review_body", "review_length"]]

                                               review_body  review_length
4684766  Sony DAV-HDX576WF Home Theater System  Overvie...          29418
1162842  The Old Republic (TOR) appeals to me on many v...          27967
1329744  Transformers: War for Cybertron hit the shelve...          26536
2843328  Dec 1, 2015<br />I am breaking my promise to u...          25557
1453629  Let me just start off by saying that I've been...          23723
1186865  Below is a review of this product: [[ASIN:B005...          23035
447952   Picture this. You walk into a room while a pac...          22748
1640273  Review update  1/23/13<br /><br />So I had the...          22104
1167347  \\"Monster Hunter Tri\\" is an action oriented...          22021
1119849  OK This review is going to be highly critcal. ...          21809

In [35]:
final_df["review_length"] = final_df["review_body"].str.len()
final_df = final_df[final_df["review_length"] < 5000]

In [36]:
df_sample["verified_purchase"].value_counts(normalize=True)

verified_purchase
Y    0.774252
N    0.225748
Name: proportion, dtype: float64

In [37]:
pd.crosstab(
    df_sample["verified_purchase"],
    df_sample["is_problem"],
    normalize="index"
)

is_problem                0         1
verified_purchase
N                  0.677527  0.322473
Y                  0.769130  0.230870

Doğrulanmış satın alma durumu (verified purchase), duygu durumu (sentiment) ile belirgin bir ilişki göstermektedir. Doğrulanmamış satın alımlarda daha yüksek oranda negatif yorumlar görülmektedir. Bu durum, doğrulanmamış geri bildirimlerde daha düşük güven seviyesi veya olası bir yanlılık (bias) olduğunu göstermektedir

In [38]:
final_df["verified_purchase"] = (final_df["verified_purchase"] == "Y").astype(int)

In [39]:
from collections import Counter

text = " ".join(
    df_sample[df_sample["is_problem"] == 1]["review_body"].astype(str)
)

Counter(text.lower().split()).most_common(20)

[('the', 248699),
 ('to', 126619),
 ('i', 124242),
 ('and', 112745),
 ('a', 107131),
 ('it', 88071),
 ('of', 71351),
 ('is', 68830),
 ('this', 56688),
 ('for', 52928),
 ('you', 47617),
 ('in', 47483),
 ('that', 45853),
 ('not', 43778),
 ('but', 39446),
 ('with', 36268),
 ('on', 35513),
 ('my', 35418),
 ('was', 35020),
 ('have', 33566)]

In [48]:
df_sample["text"] = (
    df_sample["review_headline"].fillna("") + " " +
    df_sample["review_body"].fillna("")
)

In [49]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r"[^a-zA-Z ]", "", text)
    return text

df_sample["text"] = df_sample["text"].apply(clean_text)

In [50]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

def remove_stopwords(text):
    return " ".join([w for w in text.split() if w not in ENGLISH_STOP_WORDS])

df_sample["text"] = df_sample["text"].apply(remove_stopwords)

In [51]:
from collections import Counter

text = " ".join(
    df_sample[df_sample["is_problem"] == 1]["text"]
)

Counter(text.lower().split()).most_common(20)

[('game', 35877),
 ('br', 24274),
 ('just', 19035),
 ('like', 17031),
 ('good', 16867),
 ('work', 14462),
 ('sound', 13576),
 ('dont', 13348),
 ('time', 11747),
 ('use', 10498),
 ('great', 10425),
 ('product', 10176),
 ('buy', 9461),
 ('play', 9398),
 ('really', 9328),
 ('quality', 8718),
 ('better', 8232),
 ('did', 7865),
 ('bought', 7665),
 ('does', 7552)]

In [56]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r"<br\s*/?>", " ", text)
    text = re.sub(r"[^a-zA-Z ]", "", text)
    return text

In [57]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

In [64]:
custom_stopwords = set(ENGLISH_STOP_WORDS).union({"br", "dont", "did", "does", "im", "just", "didnt", "really", "got", "doesnt"})

In [65]:
def remove_stopwords(text):
    return " ".join([
        w for w in text.split()
        if w not in custom_stopwords
    ])

df_sample["text"] = df_sample["text"].apply(remove_stopwords)

In [66]:
from collections import Counter

text = " ".join(
    df_sample[df_sample["is_problem"] == 1]["text"]
)

Counter(text.lower().split()).most_common(20)

[('game', 35877),
 ('like', 17031),
 ('good', 16867),
 ('work', 14462),
 ('sound', 13576),
 ('time', 11747),
 ('use', 10498),
 ('great', 10425),
 ('product', 10176),
 ('buy', 9461),
 ('play', 9398),
 ('quality', 8718),
 ('better', 8232),
 ('bought', 7665),
 ('games', 7444),
 ('money', 6764),
 ('bad', 6354),
 ('new', 6349),
 ('way', 6267),
 ('headphones', 6248)]

In [67]:
bad_words = Counter(" ".join(
    df_sample[df_sample["is_problem"] == 1]["text"]
).split())

good_words = Counter(" ".join(
    df_sample[df_sample["is_problem"] == 0]["text"]
).split())

In [68]:
bad_words - good_words

Counter({'waste': 2627,
         'poor': 2222,
         'return': 2108,
         'terrible': 1548,
         'disappointed': 1407,
         'stopped': 1354,
         'junk': 1273,
         'horrible': 1239,
         'worst': 1238,
         'returned': 1116,
         'star': 1041,
         'broke': 1013,
         'refund': 951,
         'ok': 908,
         'defective': 844,
         'useless': 828,
         'garbage': 749,
         'disappointing': 741,
         'crap': 711,
         'returning': 690,
         'worse': 664,
         'boring': 654,
         'awful': 628,
         'broken': 612,
         'okay': 541,
         'disappointment': 524,
         'ea': 516,
         'beware': 509,
         'poorly': 498,
         'unfortunately': 495,
         'warranty': 463,
         'sucks': 447,
         'failed': 444,
         'send': 428,
         'lasted': 410,
         'bad': 406,
         'worthless': 374,
         'trash': 363,
         'wasted': 349,
         'months': 329,
         'sent': 321,
         'drm': 314,
         'buyer': 272,
         'cheaply': 268,
         'static': 248,
         'died': 244,
         'frustrating': 240,
         'contacted': 226,
         'guess': 224,
         'quit': 221,
         'faulty': 213,
         'unusable': 208,
         'joke': 205,
         'sending': 205,
         'stupid': 199,
         'hopes': 196,
         'meh': 192,
         'luck': 188,
         'unable': 187,
         'mediocre': 187,
         'policy': 177,
         'unplayable': 173,
         'unacceptable': 170,
         'description': 164,
         'hoping': 157,
         'freezes': 155,
         'impossible': 143,
         'lame': 142,
         'contact': 142,
         'error': 138,
         'shame': 138,
         'misleading': 135,
         'sad': 133,
         'failure': 131,
         'apparently': 130,
         'message': 129,
         'ruined': 128,
         'pos': 127,
         'piece': 121,
         'pathetic': 114,
         'servers': 114,
         'advertising': 112,
         'unreliable': 111,
         'crashes': 110,
         'fell': 107,
         'randomly': 107,
         'sadly': 106,
         'attempted': 106,
         'false': 105,
         'barely': 104,
         'mistake': 104,
         'ripoff': 104,
         'spore': 103,
         'reset': 102,
         'crappy': 102,
         'lemon': 101,
         'pointless': 101,
         'buggy': 100,
         'repair': 98,
         'defect': 98,
         'unhappy': 97,
         'stops': 97,
         'fake': 94,
         'nope': 91,
         'fix': 90,
         'threw': 90,
         'dissapointed': 89,
         'stinks': 88,
         'scam': 88,
         'flawed': 87,
         'avoid': 87,
         'avail': 87,
         'shoddy': 82,
         'rent': 82,
         'lousy': 81,
         'alright': 81,
         'froze': 81,
         'subpar': 80,
         'execution': 80,
         'dud': 80,
         'falls': 79,
         'refunded': 79,
         'expired': 78,
         'cracked': 76,
         'dissatisfied': 75,
         'skips': 74,
         'fails': 74,
         'refused': 74,
         'rma': 73,
         'emails': 72,
         'horrid': 71,
         'letdown': 71,
         'doa': 70,
         'disconnected': 69,
         'cuts': 66,
         'paperweight': 66,
         'weeks': 65,
         'lesson': 65,
         'receipt': 65,
         'horrendous': 63,
         'securom': 62,
         'badly': 60,
         'horribly': 60,
         'bland': 60,
         'eh': 60,
         'fail': 59,
         'refuses': 59,
         'headache': 58,
         'unplugged': 58,
         'repeatedly': 58,
         'nonexistent': 58,
         'incomplete': 58,
         'activation': 58,
         'defeats': 57,
         'ridiculous': 57,
         'disapointed': 57,
         'ugh': 57,
         'intermittently': 57,
         'respond': 56,
         'ashamed': 56,
         'jr': 55,
         'exchanged': 55,
         'unresponsive': 55,
         'upset': 54,
         'excuse': 53,
         'customers': 53,
         'troubleshooting': 52,
         'support': 51,
         'email': 51,
         'frustration': 50,
         'simcity': 49,
         'screwed': 49,
         'credit': 48,
         'reinstall': 48,
         'insult': 48,
         'bulb': 47,
         'atrocious': 47,
         'melted': 46,
         'cheated': 46,
         'uninstalled': 46,
         'buzzing': 46,
         'joep': 46,
         'suck': 45,
         'unfinished': 45,
         'overrated': 45,
         'activision': 45,
         'pissed': 44,
         'freezing': 44,
         'crackling': 44,
         'utterly': 44,
         'flickering': 44,
         'rushed': 44,
         'frustrated': 43,
         'utter': 43,
         'advertisement': 43,
         'restart': 43,
         'manufacturer': 43,
         'exchange': 43,
         'shorted': 43,
         'contacting': 43,
         'restocking': 42,
         'rubbish': 42,
         'counterfeit': 42,
         'dissapointment': 41,
         'happened': 41,
         'attempts': 41,
         'unbearable': 41,
         'unreadable': 41,
         'ruins': 40,
         'inferior': 40,
         'wtf': 40,
         'eas': 39,
         'fragile': 39,
         'intermittent': 39,
         'tomorrow': 38,
         'register': 38,
         'pile': 38,
         'rip': 38,
         'unsatisfied': 38,
         'attempt': 37,
         'recognize': 37,
         'tinny': 37,
         'corrupted': 37,
         'forums': 37,
         'pictured': 37,
         'deceiving': 37,
         'malfunctioning': 37,
         'unlucky': 37,
         'abysmal': 36,
         'inaccurate': 36,
         'painful': 36,
         'uninspired': 36,
         'postage': 36,
         'deleted': 36,
         'sair': 36,
         'repetitive': 35,
         'bummer': 35,
         'redeeming': 35,
         'brittle': 34,
         'february': 34,
         'assumed': 34,
         'resolve': 34,
         'excited': 33,
         'fluke': 33,
         'hurts': 33,
         'disgusted': 33,
         'auction': 33,
         'authorized': 33,
         'forced': 32,
         'deceptive': 32,
         'ignored': 32,
         'wast': 32,
         'hyped': 32,
         'treyarch': 32,
         'piracy': 32,
         'refundbr': 32,
         'daoc': 32,
         'inadequate': 31,
         'burnt': 31,
         'nonfunctional': 31,
         'stating': 31,
         'severely': 31,
         'crapped': 31,
         'soe': 31,
         'disconnects': 31,
         'manufacturing': 30,
         'glitchy': 30,
         'disapointing': 30,
         'incompatible': 29,
         'incorrect': 29,
         'dissapointing': 29,
         'properly': 28,
         'disapointment': 28,
         'fee': 28,
         'chinese': 28,
         'concept': 28,
         'junkbr': 28,
         'uninstall': 28,
         'lied': 28,
         'defected': 28,
         'ariaz': 28,
         'inconsistent': 27,
         'advise': 27,
         'laggy': 27,
         'supervisor': 27,
         'resetting': 27,
         'laughable': 27,
         'putt': 27,
         'aya': 27,
         'unpleasant': 26,
         'restarting': 26,
         'hazard': 26,
         'reply': 26,
         'responding': 26,
         'suddenly': 26,
         'boo': 26,
         'decides': 26,
         'altogether': 26,
         'rude': 26,
         'knockoff': 26,
         'displeased': 26,
         'disaster': 26,
         'bin': 26,
         'fraud': 26,
         'hackers': 26,
         'plagued': 26,
         'uselessbr': 26,
         'mohikan': 26,
         'falsely': 25,
         'chore': 25,
         'reinstalled': 25,
         'frustratingbr': 25,
         'mobs': 25,
         'disgrace': 24,
         'substandard': 24,
         'rendering': 24,
         'marketing': 24,
         'manufacture': 24,
         'cbr': 24,
         'steve': 24,
         'cursor': 24,
         'garbagebr': 24,
         'maxis': 24,
         'bait': 24,
         'authorization': 24,
         'dumbed': 23,
         'smell': 23,
         'irritating': 23,
         'endgame': 23,
         'rep': 23,
         'crippled': 23,
         'unintuitive': 23,
         'deadline': 23,
         'unhelpful': 23,
         'mua': 23,
         'aggravating': 22,
         'tries': 22,
         'coby': 22,
         'riddled': 22,
         'unstable': 22,
         'rental': 22,
         'banned': 22,
         'ripped': 22,
         'freeze': 22,
         'qa': 22,
         'ubi': 22,
         'activations': 22,
         'crackles': 21,
         'malfunctioned': 21,
         'heed': 21,
         'suggestions': 21,
         'abruptly': 21,
         'miserable': 21,
         'unfortunate': 21,
         'wheres': 21,
         'draconian': 21,
         'promising': 21,
         'ward': 21,
         'rebooting': 21,
         'wasting': 21,
         'miserably': 21,
         'inability': 21,
         'shallow': 21,
         'slapped': 21,
         'idiotic': 21,
         'swg': 21,
         'sporadically': 21,
         'unimpressed': 21,
         'distorts': 20,
         'forum': 20,
         'warned': 20,
         'unforgivable': 20,
         'lags': 20,
         'renders': 20,
         'requesting': 20,
         'underwhelmed': 20,
         'turd': 20,
         'straw': 20,
         'blatant': 20,
         'misrepresented': 20,
         'quits': 20,
         'kcc': 20,
         'glorified': 19,
         'malfunction': 19,
         'arrival': 19,
         'ubisoft': 19,
         'explanation': 19,
         'worsebr': 19,
         'inexcusable': 19,
         'sigh': 19,
         'waist': 19,
         'nothingbr': 19,
         'saddle': 19,
         'infuriating': 19,
         'chessmaster': 19,
         'programmers': 18,
         'unoriginal': 18,
         'causes': 18,
         'fried': 18,
         'reload': 18,
         'shouldve': 18,
         'hunk': 18,
         'lux': 18,
         'policies': 18,
         'refunds': 18,
         'landfill': 18,
         'admitted': 18,
         'ineffective': 18,
         'datel': 18,
         'retarded': 17,
         'testers': 17,
         'redeem': 17,
         'sloppy': 17,
         'staticky': 17,
         'hazardous': 17,
         'pitiful': 17,
         'august': 17,
         'july': 17,
         'imitation': 17,
         'muddled': 17,
         'smelled': 17,
         'bbb': 17,
         'upsetting': 17,
         'lifeless': 17,
         'attempting': 17,
         'thq': 17,
         'warped': 17,
         'cu': 17,
         'reboots': 17,
         'consumers': 16,
         'sluggish': 16,
         'injury': 16,
         'uninstalling': 16,
         'backbr': 16,
         'plague': 16,
         'acknowledge': 16,
         'steer': 16,
         'overhyped': 16,
         'horriblebr': 16,
         'greed': 16,
         'irritated': 16,
         'bewarebr': 16,
         'ehhh': 16,
         'uninteresting': 16,
         'qb': 16,
         'gm': 16,
         'ehh': 16,
         'refunding': 16,
         'hmg': 16,
         'gumby': 15,
         'glaring': 15,
         'lamebr': 15,
         'downgrade': 15,
         'agreed': 15,
         'kane': 15,
         'mailed': 15,
         'eabr': 15,
         'unavailable': 15,
         'terribly': 15,
         'corporate': 15,
         'annoyingbr': 15,
         'existent': 15,
         'scammed': 15,
         'blizzards': 15,
         'downhill': 15,
         'invalid': 15,
         'seam': 15,
         'erratic': 15,
         'bogus': 15,
         'dailies': 15,
         'unbreakable': 15,
         'rejected': 15,
         'dreadful': 15,
         'resistive': 15,
         'overheated': 15,
         'recourse': 15,
         'sincerely': 15,
         'maddening': 15,
         'disappointingbr': 15,
         'dh': 15,
         'apart': 14,
         'passable': 14,
         'request': 14,
         'abused': 14,
         'repeated': 14,
         'flicker': 14,
         'ridiculousbr': 14,
         'tiberium': 14,
         'interferes': 14,
         'wiggled': 14,
         'crackle': 14,
         'dissappointing': 14,
         'lawsuit': 14,
         'troubleshoot': 14,
         'renting': 14,
         'inoperable': 14,
         'deadbr': 14,
         'discription': 14,
         'poorbr': 14,
         'filed': 14,
         'unimpressive': 14,
         'tossed': 14,
         'emptor': 14,
         'flaky': 14,
         'reformat': 14,
         'sux': 14,
         'unimaginative': 14,
         'aggravation': 14,
         'godawful': 14,
         'dumpster': 14,
         'flashed': 14,
         'homecoming': 14,
         'olive': 14,
         'brs': 14,
         'brea': 14,
         'repairs': 13,
         'muffled': 13,
         'reapers': 13,
         'emailed': 13,
         'causing': 13,
         'threads': 13,
         'humming': 13,
         'sorely': 13,
         'lackluster': 13,
         'responded': 13,
         'gw': 13,
         'mediocrity': 13,
         'nada': 13,
         'resorted': 13,
         'mislead': 13,
         'requests': 13,
         'flickers': 13,
         'iw': 13,
         'relations': 13,
         'disappointmentbr': 13,
         'minimally': 13,
         'smh': 13,
         'stoped': 13,
         'unuseable': 13,
         'warlords': 13,
         'moo': 13,
         'nonexistant': 13,
         'kinnect': 13,
         'flickered': 13,
         'mythic': 13,
         'pulsing': 13,
         'serviced': 13,
         'spyware': 13,
         'nonintuitive': 13,
         'wots': 13,
         'dev': 12,
         'crapbr': 12,
         'credited': 12,
         'exposing': 12,
         'caused': 12,
         'embarrassed': 12,
         'reinstalling': 12,
         'corroded': 12,
         'expires': 12,
         'luckbr': 12,
         'dishonest': 12,
         'repackaged': 12,
         'appalling': 12,
         'costumer': 12,
         'diary': 12,
         'crafters': 12,
         'rethink': 12,
         'unsatisfying': 12,
         'returnable': 12,
         'turtles': 12,
         'losses': 12,
         'incompetent': 12,
         'garbled': 12,
         'criminal': 12,
         'scratchy': 12,
         'spawning': 12,
         'pspgo': 12,
         'shit': 12,
         'duped': 12,
         'wrinkles': 12,
         'sorry': 11,
         'questionable': 11,
         'glue': 11,
         'april': 11,
         'crashing': 11,
         'monotonous': 11,
         'appeared': 11,
         'restarted': 11,
         'informed': 11,
         'imprecise': 11,
         'glitched': 11,
         'defectivebr': 11,
         'pitched': 11,
         'tini': 11,
         'awfulbr': 11,
         'dissatisfaction': 11,
         'bugsbr': 11,
         'exchanges': 11,
         'unplayablebr': 11,
         'misled': 11,
         'df': 11,
         'fiddled': 11,
         'stupidity': 11,
         'jiggled': 11,
         'insulting': 11,
         'robbed': 11,
         'toa': 11,
         'homefront': 11,
         'raynox': 11,
         'pirated': 11,
         'ejected': 11,
         'apology': 11,
         'animus': 11,
         'apologize': 11,
         'recalled': 11,
         'mistakebr': 11,
         'splitfish': 11,
         'mixdeck': 11,
         'rpsma': 11,
         'teamsbr': 11,
         'remy': 11,
         'devs': 10,
         'smoking': 10,
         'fundamental': 10,
         'eagerly': 10,
         'restricts': 10,
         'crummy': 10,
         'dumbest': 10,
         'horrific': 10,
         'unrecognizable': 10,
         'needlessly': 10,
         'deplorable': 10,
         'farce': 10,
         'taped': 10,
         'mysteriously': 10,
         'tiresome': 10,
         'workbr': 10,
         'workingbr': 10,
         'meaningful': 10,
         'shuts': 10,
         'corrupt': 10,
         'uninspiring': 10,
         'aweful': 10,
         'hopeless': 10,
         'jiggling': 10,
         'warn': 10,
         'filing': 10,
         'indicates': 10,
         'detached': 10,
         'inexplicably': 10,
         'songbird': 10,
         'exploded': 10,
         'sucky': 10,
         'instructed': 10,
         'misery': 10,
         'stink': 10,
         'emit': 10,
         'sht': 10,
         'arbitrarily': 10,
         'hacks': 10,
         'penalty': 10,
         'qbs': 10,
         'returnexchange': 10,
         'pointlessbr': 10,
         'blames': 10,
         'invoice': 10,
         'fritz': 10,
         'pasted': 10,
         'teambr': 10,
         'athck': 10,
         'pvcu': 10,
         'lorex': 10,
         'aonuma': 10,
         'billed': 9,
         'angry': 9,
         'peice': 9,
         'housing': 9,
         'underwhelming': 9,
         'arbitrary': 9,
         'runaround': 9,
         'errands': 9,
         'rebound': 9,
         'enthusiasm': 9,
         'upc': 9,
         'nonfunctioning': 9,
         'blizzard': 9,
         'plodding': 9,
         'soso': 9,
         'inform': 9,
         'ul': 9,
         'poorer': 9,
         'haywire': 9,
         'possession': 9,
         'popping': 9,
         'confirming': 9,
         'bootleg': 9,
         'shorting': 9,
         'bazaar': 9,
         'awkwardly': 9,
         'toxic': 9,
         'submitted': 9,
         'autoaim': 9,
         'gutted': 9,
         'reimbursed': 9,
         'victim': 9,
         'ludicrous': 9,
         'firefly': 9,
         'hohum': 9,
         'railroads': 9,
         'lamest': 9,
         'travesty': 9,
         'tribal': 9,
         'reconnected': 9,
         'frogger': 9,
         'sty': 9,
         'zilch': 9,
         'representative': 9,
         'rehash': 9,
         'resemblance': 9,
         'squandered': 9,
         'suckered': 9,
         'unikeep': 9,
         'exo': 9,
         'sham': 9,
         'dysfunctional': 9,
         'resyncing': 9,
         'pisses': 9,
         'watered': 9,
         'gut': 9,
         'malware': 9,
         'bomberman': 9,
         'managers': 9,
         'jennifer': 9,
         'rvr': 9,
         'cashin': 9,
         'sucksbr': 9,
         'sector': 9,
         'scrambled': 9,
         'dantooine': 9,
         'unfixable': 9,
         'mistreated': 9,
         'deceived': 9,
         'divoom': 9,
         'fraudulent': 9,
         'inspecting': 9,
         'gamebox': 9,
         'nerfs': 9,
         'homedics': 9,
         'mts': 9,
         'blub': 9,
         'okbut': 9,
         'pripyat': 9,
         'nabi': 9,
         'wacker': 9,
         'opengl': 9,
         'xbah': 9,
         'dfm': 9,
         'drags': 8,
         'sudden': 8,
         'cmc': 8,
         'repaired': 8,
         'trashed': 8,
         'crawler': 8,
         'clueless': 8,
         'ruining': 8,
         'feb': 8,
         'radiance': 8,
         'slaves': 8,
         'bs': 8,
         'dumber': 8,
         'paperwork': 8,
         'boycott': 8,
         'marginally': 8,
         'hopeing': 8,
         'unglued': 8,
         'prolific': 8,
         'weld': 8,
         'crashed': 8,
         'pippa': 8,
         'incapable': 8,
         'discolored': 8,
         'profits': 8,
         'highpitched': 8,
         'poorest': 8,
         'worki': 8,
         'superglue': 8,
         'unwatchable': 8,
         'snapped': 8,
         'unauthorized': 8,
         'alas': 8,
         'eject': 8,
         'visibly': 8,
         'deffective': 8,
         'clarityhd': 8,
         'hacked': 8,
         'duelist': 8,
         'fips': 8,
         'cruzer': 8,
         'noname': 8,
         'semblance': 8,
         'juvenile': 8,
         'ploy': 8,
         'robocop': 8,
         'reciept': 8,
         'rof': 8,
         'hastily': 8,
         'uncomfortablebr': 8,
         'sentences': 8,
         'rebate': 8,
         'survives': 8,
         'imbalance': 8,
         'replugging': 8,
         'xwing': 8,
         'endust': 8,
         'insufficient': 8,
         'saddened': 8,
         'shameful': 8,
         'squeaking': 8,
         'screeching': 8,
         'fragmented': 8,
         'pales': 8,
         'datavision': 8,
         'duracells': 8,
         'impossiblebr': 8,
         'damper': 8,

Negatif yorumlarda sık geçen kelimeler, ürün kusurları, iade/geri ödeme şikayetleri ve teknik problemler gibi net tematik kümeler ortaya koymaktadır. Bu durum, otomatik problem yönlendirme (issue routing) sistemlerinin uygulanabilir olduğunu göstermektedir